water_site/h2os/urls.py
from django.urls import path
from datetime import datetime, timedelta
import pysnooper

from . import views
from background_task.models import Task
from .tasks import pan_checker, group_watering
app_name = 'h2os'

urlpatterns = [
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.group_create, name='create'),
    path('plants/', views.plant_list, name='plant_list'),
    path('plants/<int:pk>/', views.PlantDetailView.as_view(), name='plant-detail'),
    path("group/<int:pk>/", views.Plant_groupDetailView.as_view(),
         name="plant-group-detail")
    # wip path('group/<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
]



# this schedules the tasks when the system is run for the first time
if not Task.objects.filter(verbose_name="group_watering").exists():
    group_watering(schedule=timedelta(seconds=10), repeat=Task.DAILY, verbose_name="group_watering")
if not Task.objects.filter(verbose_name="pan_checker").exists():
    pan_checker(schedule=timedelta(seconds=10), repeat=Task.DAILY, verbose_name="pan_checker")

water_site/water_site/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from h2os import views as h2os_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', h2os_views.group_list, name="home"),
    path('about/', views.about),
    path('h2os/', include('h2os.urls')),
    path('accounts/', include('accounts.urls')),
]

water_site/h2os/models.py
from django.db import models
from django.urls import reverse
import datetime
from .hardware import waterlevel, water_pan, water_group


class Pan_data(models.Model):
    '''
    This is the model that tracks how much water gets evaporated. It logs the waterlevel at the start of the day and
    continues to keep track of the latest waterlevel. 
    it should get scheduled in ./scheduling.py
    '''
    id = models.IntegerField(primary_key=True)
    date = models.DateTimeField(auto_now=True)
    start_level = models.FloatField()
    last_level = models.FloatField()
    system_change = models.FloatField(default=0)

    def __str__(self):
        return f"{self.date} waterlevel"

    def get_absolute_url(self):  # when you're going to implement the detail view
        """Returns the url to access a particular  instance. For detailfiews and such"""
        return reverse('plant-detail', args=[str(self.date)])

    class Meta:
        '''Some extra options'''
        db_table = "Pan_data"
        verbose_name_plural = "Pan_data"

    @classmethod
    def create(cls):
        '''This sets the startlevel on creation'''
        start = waterlevel()
        data = cls(start_level=start, last_level=start)
        return data

    def log(self):
        '''
        Measures current waterlevel, adds water when below a treshold and keeps track of autosiphon and relay use. 
        needs to be scheduled in scheduling.py
        '''
        new_level = waterlevel()
        # should call a function that measures waterlevel
        if abs(new_level - self.last_level) > 100:  # ml
            self.system_change -= 100
        if new_level < 100:  # TODO: set actual min treshold level here
            water_pan()
            self.system_change += 100
        self.last_level = new_level
        self.save()

    @property
    def evaporated_today(self):
        '''
        returns how much water evaporated today
        '''
        return (self.last_level - self.start_level) + self.system_change


class Water_usage(models.Model):
    '''
    This keeps track of past water usage of groups
    '''
    id = models.IntegerField(primary_key=True)
    group = models.ForeignKey("Plant_group", on_delete=models.CASCADE)
    usage = models.FloatField(verbose_name="Water usage(L)")
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        '''How this gets named on the website'''
        return str(self.id)

    def get_absolute_url(self):  # when you're gonna implement the detail view
        """Returns the url to access a particular  instance."""
        return reverse('water-detail', args=[str(self.id)])

    class Meta:
        db_table = "Water_Usage"
        verbose_name_plural = "Water_usage"


STAGES = [
    ('initial', 'Initial planting stage'),
    ('interpolate', 'Development stage'),
    ('mid', 'Mature state'),
    ('end', 'Harvest state')
]
t1 = datetime.time(7, 0, 0)
t2 = datetime.time(17, 0, 0)


class Plant_group(models.Model):  # want to make this group
    # unique, since only one group per id
    loc_id = models.IntegerField(unique=True)
    plant = models.OneToOneField(
        "Plant", on_delete=models.PROTECT, blank=True, null=True)
    growth_stage = models.CharField(
        max_length=20, choices=STAGES, default='initial')
    growth_day = models.IntegerField()
    area = models.FloatField()  # m^2
    water_flowrate = models.FloatField()
    water_t1 = models.TimeField(default=t1)
    water_t2 = models.TimeField(default=t2)
    last_irrigated = models.DateTimeField()

    def __str__(self):
        return f"Group {self.loc_id}"

    def get_absolute_url(self):  # when you're going to implement the detail view
        """Returns the url to access a particular  instance."""
        return reverse('plant-group-detail', args=[str(self.loc_id)])

    class Meta:
        db_table = "Plantgroup"
        verbose_name_plural = "Plantgroups"

    def water_now(self):
        '''
        This waters the group. Needs to be scheduled in scheduling.py
        '''
        # DEBUG: the flow of this needs to be thought through
        evaporated = Pan_data.objects.latest('date').evaporated_today
        water_requirement = evaporated * \
            self.plant.crop_factor(self.growth_day) * self.area * 1
        # todo: add pan factor to the equation
        temp_now = datetime.datetime.now()
        now = datetime.time(temp_now.hour, temp_now.minute)
        if now >= self.water_t2:
            try:  # this is so that if the system was used for the first time after T1 time
                water_requirement -= Water_usage.objects.get(
                    group=self).usage
            except:
                pass

        relay_timer = water_requirement / self.water_flowrate
        water_group(self.loc_id, relay_timer)
        usage = Water_usage(group=self, usage=water_requirement)
        usage.save()


class Plant(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.TextField(max_length=100)
    initial_kc = models.FloatField()
    mid_kc = models.FloatField()
    end_kc = models.FloatField()
    initial_length = models.IntegerField()
    interpolate_length = models.IntegerField()
    mid_length = models.IntegerField()
    end_length = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):  # when you're going to implement the detail view
        """Returns the url to access a particular  instance."""
        return reverse('plant-detail', args=[str(self.id)])

    class Meta:
        db_table = "Plant"
        verbose_name_plural = "Plants"

    def crop_factor(self, day):
        '''
        Returns the crop factor(Kc) of a given crop and how long it's in the ground.
        parameters:
        return = float
        >> crop_factor(99)
        >> 1.04
        '''
        # determining stage
        if day < self.initial_length:
            return self.initial_kc
        elif day < self.initial_length + self.interpolate_length:
            x = day - self.initial_length
            dy = (self.mid_kc - self.initial_kc) / self.interpolate_length
            total = self.initial_kc + x * dy
            return total
        elif day < self.initial_length + self.interpolate_length + self.mid_length:
            return self.mid_kc
        else:
            return self.end_kc

water_site/h2os/forms.py
from django import forms
from . import models

class CreatePlantGroup(forms.ModelForm):
    class Meta:
        models = models.Plant_group
        fields=['loc_id','plant','growth_stage','growth_day','distance','water_flowrate','water_t1','water_t2','last_irrigated']

water_site/h2os/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .models import Plant_group, Plant
from . import forms 
from django.contrib.auth.decorators import login_required 


def group_list(request):
    all_groups = Plant_group.objects.all().order_by('loc_id')
    return render(request, 'h2os/group_list.html', {'groups': all_groups} )

def plant_list(request):
    all_plants = Plant.objects.all().order_by('id')                         # Puts all plant objects in 'id' order in array
    return render(request, 'h2os/plant_list.html', {'plants': all_plants} ) # Sends array to html for display

class Plant_groupDetailView(generic.DetailView):
    model = Plant_group

class PlantDetailView(generic.DetailView):
    model = Plant
    ## example of how to add things to context. ignore. // TODO: remove when done
    # def get_context_data(self, **kwargs):
    #     # Call the base implementation first to get the context
    #     context = super(FactuurDetailView, self).get_context_data(**kwargs)
    #     # context['korting'] = context["factuur"].Korting_percent * context["factuur"].Subtotal / 100
    #     # context["beforetax"] = context["factuur"].Subtotal - context["korting"]
    #     # context["tax"] = context["beforetax"] * 0.08
    #     return context


@login_required(login_url="/accounts/login/")       # Requires user to be logged in in order to create a group
def group_create(request):
    if request.method == 'POST':                    
        form = forms.CreatePlantGroup(request.POST) # Assigns data to form -- Add request.Files if necessary to upload files
        if form.is_valid():                         # Checks to see if form is valid
            form.save()
            return redirect('h2os:group_list')      # Redirects to group_list page
    else:
        form = forms.CreatePlantGroup()             # Assigns creation form 
    return render(request, 'h2os/group_create.html', {'form':form}) # Send form to html for display

water_site/h2os/templates/h2os/group_create.html
{% extends "base_generic.html" %}
{% block content %}
<div class="create_group">
    <h2>Create an new group</h2>
        <form class="site-form" action="{% url 'h2os:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
</div>
{% endblock %} 

water_site/h2os/templates/h2os/group_list.html
{% extends "base_generic.html" %}
{% block content %}
<h1>This is the main overview of your plants</h1>
        <p>Welcome to this page.</p>
        <div class = 'groups'>
            {% for group in groups %}
            <div class = 'group'> 
                <h2>{{group.loc_id}}. {{group.plant}}</h2>
                <p>This plant is located at patch number {{group.loc_id}}.<br>
                    This plant is in growth stage {{group.growth_stage}} on day {{group.growth_day}}.<br>
                    Last watered at {{group.last_irrigated}} for the amount of x liters. <br>
                    Irrigation times are set at {{group.water_t1}} and {{group.water_t2}} .
                </p>
                

            </div>
            {% endfor %}
{% endblock %}

water_site/h2os/templates/h2os/home.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Watersite: H2OS home</title>
    </head>
    <body>
        <h1>This is the main overview of your plants</h1>
        <p>Welcome to this page.</p>
        <div class = 'groups'>
            {% for group in groups %}
            <div class = 'group'> 
                <h2>{{group.loc_id}}. {{group.plant}}</h2>
                <p>This plant is located at patch number {{group.loc_id}}.<br>
                    This plant is in growth stage {{group.growth_stage}} on day {{group.growth_day}}.<br>
                    Last watered at {{group.last_irrigated}} for the amount of x liters. <br>
                    Irrigation times are set at {{group.water_t1}} and {{group.water_t2}} .
                </p>
                

            </div>
            {% endfor %}
        </div>
    </body>
</html>

water_site/h2os/templates/h2os/plant_detail.html
{% extends "base_generic.html" %}


{% block content %}
{% load static %}
{% load l10n %}
<h1>{{plant.name}}</h1>
<table>
  <tr>
    <th>Stage</th>
    <th>Length</th>
    <th>Crop Factor</th>
  </tr>
  <tr>
    <td>Initial</td>
    <td>{{plant.initial_length}}</td>
    <td>{{plant.initial_kc}}</td>
  </tr>

  <tr>
    <td>Growth</td>
    <td>{{plant.interpolate_length}}</td>
    <td>{{plant.initial_kc}} - {{plant.mid_kc}}</td>
  </tr>

  <tr>
    <td>Mid</td>
    <td>{{plant.mid_length}}</td>
    <td>{{plant.mid_kc}}</td>
  </tr>

  <tr>
    <td>End</td>
    <td>{{plant.end_length}}</td>
    <td>{{plant.end_kc}}</td>
  </tr>

</table>


{% endblock %}

water_site/h2os/templates/h2os/plant_group_detail.html
{% extends "base_generic.html" %}


{% block content %}
{% load static %}
{% load l10n %}


<h2>{{plant_group.loc_id}}. {{plant_group.plant}}</h2>
<p>This plant is located at patch number {{plant_group.loc_id}}.<br>
    This plant is in growth stage {{plant_group.growth_stage}} on day {{plant_group.growth_day}}.<br>
    Last watered at {{plant_group.last_irrigated}} for the amount of x liters. <br>
    Irrigation times are set at {{plant_group.water_t1}} and {{plant_group.water_t2}} .
</p>


</div>


{% endblock %}

water_site/h2os/templates/h2os/plant_list.html
{% extends "base_generic.html" %}
{% block content %}

<h1>This is the list overview of all plants.</h1>
        <p>Welcome to this page.</p>
        <div class = 'plants'>
            {% for plant in plants %}
            <div class = 'plant'> 
                <p><a href="{% url 'h2os:plant-detail' plant.pk %}">{{plant.id}}. {{plant.name}}</a></p>
            </div>
{% endfor %}
{% endblock %}