water_site/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

water_site/h2os/urls.py
from django.urls import path
from datetime import datetime, timedelta
import pysnooper

from . import views
from background_task.models import Task
from .tasks import pan_checker, group_watering
app_name = 'h2os'

urlpatterns = [
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.group_create, name='create'),
    path('plants/', views.plant_list, name='plant_list'),
    path('plants/<int:pk>/', views.PlantDetailView.as_view(), name='plant-detail'),
    path("group/<int:pk>/", views.Plant_groupDetailView.as_view(),
         name="plant-group-detail")
    # wip path('group/<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
]



# this schedules the tasks when the system is run for the first time
if not Task.objects.filter(verbose_name="group_watering").exists():
    group_watering(schedule=timedelta(seconds=10), repeat=Task.DAILY, verbose_name="group_watering")
if not Task.objects.filter(verbose_name="pan_checker").exists():
    pan_checker(schedule=timedelta(seconds=10), repeat=Task.DAILY, verbose_name="pan_checker")

water_site/water_site/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from h2os import views as h2os_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', h2os_views.group_list, name="home"),
    path('about/', views.about),
    path('h2os/', include('h2os.urls')),
    path('accounts/', include('accounts.urls')),
]

water_site/water_site/views.py
from django.shortcuts import render
from django.http import HttpResponse

app_name='water_site'

def homepage(request):
    return render(request,'water_site/homepage.html')
def about(request):
    return render(request,'about.html')

water_site/water_site/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>H2OS</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}

</head>
<body>
  {% include "navigation.html" %}
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
              </form>
          </li>
          <li><a href="{% url 'h2os:create' %}" class="highlight">Create new group</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        {% endif %}
      </ul>
  </nav>
  </header>
  <p>TIME (debug purpose): {% now "jS F Y H:i" %} </p> 
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

water_site/water_site/templates/navigation.html
<!-- navigation.html.j2 -->
<nav>
    <ul>
        <li><a href="{% url 'home'%}">All groups</a></li>
        <li><a href="{% url 'h2os:plant_list'%}">Plants</a></li>
    </ul>
</nav>

water_site/water_site/templates/plant_detail.html
{% extends "base_generic.html" %}


{% block content %}
{% load static %}
{% load l10n %}
<h1>{{plant.name}}</h1>
<table>
  <tr>
    <th>Klant</th>
    <th>{{factuur.Klant_ID}}</th>
  </tr>
  <tr>
    <td>Datum</td>
    <td>{{ factuur.Date|date:"D d/m/Y G:i" }}</td>
  </tr>
</table>

<br>
<br>
<h2>Order</h2>
<table>
  <tr>
    <th>Product</th>
    <th>Aantal</th>
    <th>Prijs</th>
  </tr>
  {% for order in factuur.Orders.all %}
  <tr>
    <td>{{order.Voorraad_ID}}</td>
    <td>{{order.Amount}}</td>
    <td>SRD {{order.Prijs |floatformat:2}}</td>
  </tr>
  {% endfor %}
  <tr>
    <td>Subotaal</td>
    <td>
    </td>
    <td>SRD {{factuur.Subtotal |floatformat:2}}</td>
  </tr>
  <tr>
    <td>Korting</td>
    <td>{{factuur.Korting_percent}} %</td>
    <td></td>
  </tr>
  <tr>
    <td>Belasting</td>
    <td>8%</td>
    <td></td>
  </tr>
  <tr>
    <td>Totaal</td>
    <td></td>
    <td>SRD {{factuur.Total |floatformat:2}}</td>
  </tr>
</table>


{% endblock %}